errors.title=LicenceManager Error
errors.license.desktop = <html><body><p>Opening files in this platform is not supported. </p><a href=%s>Please open it yourself &lt;-&gt;</a></body></html>
errors.license = Error displaying license report: %s