errors.title=ERROR!!
errors.cannotSave=Unable to save birthday list or configuration! (%s)
errors.instanceAlreadyRunning=Another instance is already running.

trayIcon.title=Birthday Reminder

popup.open=Open
popup.exit=Exit

messages=Wish them a good day!|Celebrate them!|Wish them well!|Congratulate them!|Greet them a happy birthday!|\
  Send some good vibes to them!|Let them know you're thinking about them!|Go cheer them up!

notify.title=%s's birthday!!!
notify.content=Today is %s's birthday! They are %d years old! %s

notify.late.content.yesterday=Yesterday was %s's birthday! They are now %d years old.
notify.late.content.more=%s's birthday was %d days ago! They are now %d years old.

notify.before.caption=I just want to let you know...
notify.before.text.tomorrow=Tomorrow is %s's birthday!
notify.before.text.more=%s's birthday will be in %d days!