dialog.add=Add
dialog.remove=Remove
dialog.edit=Edit
dialog.notify.config=Config
dialog.close=Close
dialog.save=Save
dialog.save.confirm=Do you want to save the changes?
dialog.cancel=Cancel
dialog.more=>
dialog.open=Open

dialog.remove.confirm=Are you sure you want to remove %s from your birthday list?