about.title = Birthday Reminder
about.content = <html><body><p>Birthday Reminder is a little program that helps you never forget any of your friends' birthdays!</p><p>Licensed under the MIT License: Copyright (c) 2025 brickwall2900</p><p>Version: %s</p></body></html>

# used in XML declaration
about.header = About
about.license = Licenses
about.darkMode = Dark Mode