editor.dialog.title=Edit %s's birthday...
editor.dialog.fields.name=Name: 
editor.dialog.fields.date=Date: 
editor.dialog.fields.enabled=Enabled: 
editor.dialog.fields.customMessage=Custom Message: 
editor.dialog.fields.override=Override Config: 

editor.dialog.fields.name.tip=Who's the name of this person?
editor.dialog.fields.date.tip=When's their birthday? Dates should be formatted as such...%s
editor.dialog.fields.enabled.tip=Should this birthday be reminded and notified?
editor.dialog.fields.customMessage.tip=What message do you want to say when notified?
editor.dialog.fields.override.tip=Specifies how the birthday should be notified specifically for this birthday.