notify.editor.dialog.title=Notifier Editor
notify.editor.dialog.daysBeforeReminder=Days before reminder: 
notify.editor.dialog.birthdaySoundLabel=Sound path: 
notify.editor.dialog.birthdaySound.fileType=WAV File (.wav)
notify.editor.dialog.daysBeforeReminder.tip=Specifies the number of days in advance to remind you of people's/this person's birthdays.
notify.editor.dialog.birthdaySound.tip=The location of the sound file played when today's their birthday.